Table Classroom {
  id varchar [pk]
  name varchar
  capacity int
  status varchar
  semester varchar [ref: > Semester.id]
}

Table Course {
  id varchar [pk]
  name varchar
  min_teachers integer
  max_teachers integer
}

Table Section {
  id varchar [pk]
  course_id varchar [ref: > Course.id]
  name varchar
}

Table Teacher {
  id varchar [pk]
  name varchar
  status varchar
  semester varchar [ref: > Semester.id]
}

Table Semester {
  id varchar [pk]
  name varchar
  start_time time
  end_time time
}

Table CoursePreference {
  id varchar [pk]
  semester varchar [ref: > Semester.id]
  teacher_id varchar [ref: > Teacher.id]
  teaching_registration_id varchar [ref: > TeacherRegistration.id]
  course_id varchar [ref: > Course.id]
  preference_value int
}

Table TimePreference {
  id varchar [pk]
  teacher_id varchar [ref: > Teacher.id]
  teaching_registration_id varchar [ref: > TeacherRegistration.id]
  semester varchar [ref: > Semester.id]
  period enum
  day enum
  preference_value int
}


Table TeacherRegistration {
  id varchar [pk]
  teacher_id varchar [ref: > Teacher.id]
  semester varchar [ref: > Semester.id]
  status varchar
  max_courses int
}

Table Schedule {
  id varchar [pk]
  semester varchar [ref: > Semester.id]
  teacher_id varchar [ref: > Teacher.id]
  section_id varchar [ref: > Section.id]
  room_id varchar [ref: > Classroom.id]
  day enum
  period enum
}
